import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@/app/globals.css";
import { SidebarMain } from "@/components/dashboard/sidebar-main";
import { NavbarMain } from "@/components/dashboard/navbar-main";
import { auth } from "@/services/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Dashboard | Stonxis',
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} antialiased `} suppressHydrationWarning>
        <div className="flex">
          <SidebarMain />
          <div className="flex-1 lg:ml-56">
            <NavbarMain user={session?.user} />
            <div className="px-4 py-4 mt-18">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
